### ISSUE TITLE
Link to Medium article

### ISSUE THREAD

**Issue by kcostya** [tech4242/docker-hadoop-hive-parquet#4]
Could you please add the link to the [medium article ](https://towardsdatascience.com/making-big-moves-in-big-data-with-hadoop-hive-parquet-hue-and-docker-320a52ca175)
And thanks for the tutorial!

**Comment by tech4242** [comment]
Somehow this issue slipped my mind. In any case the tutorial link is in the GH description:

![image](https://user-images.githubusercontent.com/5933291/126870222-a6851b80-e1ef-462a-a999-0515669c3929.png)
